sudo: false
language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - clang

compiler:
  - clang
  - gcc

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test_hutrua
